name: Publish Package to GitHub
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish package on main
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          check-latest: true
          registry-url: 'https://npm.pkg.github.com'
          scope: '@eclipse-velocitas'
      - run: npm ci
      - run: npm run build
      - run: npm publish
        if: contains('refs/heads/main', github.ref)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
